[package]
name = "mitograph"
version = "0.1.0"
edition = "2021"

[dependencies]
bio = "2.0.1"
flate2 = "1.0.30"
clap = { version = "4.5.1", features = ["derive"] }
serde_json = "1.0.120"
serde = "1.0.204"
rust-htslib = "0.44.1"
